### ISSUE TITLE
[Neat URL] Middle click behavior on Google search

### ISSUE THREAD

**Issue by gwarser** [Smile4ever/firefoxaddons#42]
Firefox 55 or 58
Neat URL 2.0.4

When I search for something in Google, and then middle click on result to open in new tab, both tabs are redirected to new page.

Example search 
`https://www.google.pl/search?q=dom.push.enabled&ie=utf-8&oe=utf-8&client=firefox-b&gfe_rd=cr&dcr=0&gws_rd=cr`
`https://www.google.com/search?q=dom.push.enabled&ie=utf-8&oe=utf-8&client=firefox-b&gfe_rd=cr&dcr=0&fg=1`

**Comment by Smile4ever** [comment]
Please test this in a clean profile and report back. I don't understand what's happening right now with your explaination, but honestly I cannot believe Neat URL causes this behaviour. Please prove me wrong if you want.

**Comment by gwarser** [comment]
This was tested on Stable Firefox on clean profile. I tested just now, again, and no change.

- on Nightly - open about:profiles
- remove "stable" profile with files
- create new "stable" profile
- launch stable Firefox `./firefox -P stable -no-remote`
- verify it's clean (no extension), about:support -> Open directory button opens newly crated directory
- install Neat URL from about:addons
- type "webnotifications" in search bar -> enter
- middle click on first not-ad link "Using the Notifications API - Web APIs | MDN"
- both pages opens `https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API` 
- click on Neat URL icon to disable
- reload page or perform new search 
- middle click have expected behavior 

I forgot to add - I'm on Linux Mint 18.2. Maybe this change something?

**Comment by gwarser** [comment]
This does not apply to all search results. For example for ["webnotification"](https://www.google.pl/search?q=webnotification&ie=utf-8&oe=utf-8&client=firefox-b&gfe_rd=cr&dcr=0), two links to github are ok, but third to developer.mozilla.org is affected.

Probably caused by `, ved@google.*` - when removed, all seems to be OK.

**Comment by Smile4ever** [comment]
I was able to confirm that ved@google.* is indeed the problem. I will investigate the cause and release a new version of Neat URL which contains the fix for this problem.

**Comment by Smile4ever** [comment]
Update: ved@google.* is not the problem. Its the way I handle links to mozilla.org.. I have an idea in my mind on how to solve this. I will keep you updated.

**Comment by Smile4ever** [comment]
https://github.com/Smile4ever/firefoxaddons/commit/35aca5d4f160c1dc2c30f2daed6f0eb596b05787 fixes this issue. It is available in Neat URL 2.0.5 (which will soon be visible on addons.mozilla.org). Closing this issue 👍

**Comment by gwarser** [comment]
>Its the way I handle links to mozilla.org.

Why links to mozilla.org are not cleaned?

Example here https://blog.mozilla.org/firefox/introducing-firefox-multi-account-containers/ ([The Firefox Multi-Account Containers extension](https://addons.mozilla.org/firefox/addon/multi-account-containers/?utm_source=blog.mozilla.org&utm_campaign=firefox_frontier&utm_medium=referral) )

I know that webextension addons are not working on addons.mozilla.org, but there should be no problem on blog.mozilla.org. My other extensions work fine here - for example smartUp Gestures.

**Comment by Smile4ever** [comment]
It's not the origin URL that matters, it's the target URL. And yes, you're right: addons.mozilla.org is only cleaned on refresh (F5). It's a known issue that needs fixing in Neat URL. Addons.mozilla.org is handled differently because webRequest does not support priviledged domains, so that's probably the cause.

**Comment by gwarser** [comment]
This bug is back. Additionally when I use left click, I cannot go back - I must click twice on back button to go back.

**Comment by Smile4ever** [comment]
I cannot reproduce this issue using Neat URL 2.1.0. Can you state exactly what you did?

**Comment by gwarser** [comment]
First one is like in bug report. Middle click on https://addons.mozilla.org/firefox/addon/multi-account-containers/?utm_source=blog.mozilla.org&utm_campaign=firefox_frontier&utm_medium=referral opens link in current and new page.

Second is weird - sometimes is ok, sometimes I end up on blank `moz-extension://dbd410de-ad84-45a2-96c9-ee258b5aa54c/_generated_background_page.html`, and sometimes something is "one click back" in history, and redirects me "forward".

**Comment by gwarser** [comment]
- clean profile
- install 2.0.5
- restart browser
- open https://addons.mozilla.org/firefox/addon/multi-account-containers/?utm_source=blog.mozilla.org&utm_campaign=firefox_frontier&utm_medium=referral - no cleaning, but no other issues
- go to about:addons and select "Check for updates" from "Gear" menu - 2.1.0 should be installed
- reload this issue page
- middle click https://addons.mozilla.org/firefox/addon/multi-account-containers/?utm_source=blog.mozilla.org&utm_campaign=firefox_frontier&utm_medium=referral
- black tab with URL `moz-extension://944d85cf-0280-47c2-8477-0fb0b58d3bc4/_generated_background_page.html` will open in new tab, "Neat URL" badge is visible in address bar

**Comment by Smile4ever** [comment]
Alright, fixed in 2.1.1. Please try that version once it's available on AMO (I've submitted it already, it just needs to be approved).

**Comment by gwarser** [comment]
No blank page anymore.

I still see sometimes, that current page and new one are redirected to new url. 

When I middle click -> wait for new tab to load -> middle click again -> (repeat) -> I can see that two of these newly opened tabs are reloading.

**Comment by Smile4ever** [comment]
If you can reproduce "sometimes" in a reliable way, I'm happy to look at it again. Please open a new issue then.
